# This is default sample specification
# Feel free to change it
# Call flowpdk showdoc pluginspec to see the list of available fields and their description
pluginName: 'SharedCredentials'
version: '1.0.0'
description: 'No description'
author: 'No Name'
authorUrl: 'No support URL'
category: 'Utilities'

# Plugin configuration description
configuration:
  # This is a declaration for the plugin configuration
  shell: 'ec-perl'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: null
    label: Description
  -
    name: endpoint
    documentation: Third-party endpoint to connect to.
    required: false
    type: entry
    label: null
  -
    name: credential
    documentation: 
    required: true
    type: credential
    label: Credential

procedures:
-
  name: 'Sample Procedure'
  description: 'Sample procedure description'
  # configuration field will be generated automatically
  hasConfig: true
  shell: 'ec-perl'
  parameters:
  -
    name: applicationPath
    documentation: Path to the application
    required: true
    type: entry
    label: Application Path
  outputParameters:
    deployed: 'JSON representation of the deployed application'
